### ISSUE TITLE
error: TypeError: f.findLast is not a function

### ISSUE THREAD

**Issue by Yakov5776** [tanishqmanuja/apkmirror-downloader#14]
```node .\bin\apkmd.cjs config.json
APKMirror Downloader v1.0.6
TypeError: f.findLast is not a function
    at C:\Users\Yakov\Downloads\apkmirror-downloader\bin\apkmd.cjs:31:395
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Could not find stable version
    at pb (C:\Users\Yakov\Downloads\apkmirror-downloader\bin\apkmd.cjs:29:1304)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\Yakov\Downloads\apkmirror-downloader\bin\apkmd.cjs:31:225

Press any key to exit ...
```

I used the default config provided in the README.md and running nodeJS version 16.13.0.
I appreciate you for maintaining.

**Comment by tanishqmanuja** [comment]
I suspect that upgrading node version would fix this. Because `.findLast` and other array method were added in node 18.

Also you could replace arr.findLast with equivalent code like arr[arr.length - 1] for now.

**Comment by Yakov5776** [comment]
That seems to be the issue, thank you!
